urls.py
from django.conf.urls import url
import django_auth.views
from .views import UserProfileCRUDL

urlpatterns = [
    url(r'^$', django_auth.views.index, name='index'),
    url(r'^login/$', django_auth.views.index),
    url(r'^auth/$', django_auth.views.dj_auth),
    url(r'^invalid/$', django_auth.views.invalid),
    url(r'^logout/$', django_auth.views.logout, name='logout'),
    url(r'^register/$', django_auth.views.register_user),
    url(r'^register_success/$', django_auth.views.register_success),
    url(r'^confirm/(?P<activation_key>\w+)/$', django_auth.views.confirm),
    url(r'^confirm_reg_code/$', django_auth.views.confirm_reg_code),
    url(r'^confirm_login_code/$', django_auth.views.confirm_login_code)
]
urlpatterns += UserProfileCRUDL().as_urlpatterns()

forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CustomRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    phone = forms.CharField(required=True)
    terms_of_service = forms.BooleanField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'phone', 'terms_of_service')

    def save(self, commit=True):
        user = super(CustomRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.phone = self.cleaned_data['phone']
        user.terms_of_service = self.cleaned_data['terms_of_service']

        if commit:
            # User is inactive on registration
            user.is_active = False
            user.save()

        return user

templates/base.html
<!DOCTYPE html>
<html >

  <head>

    <meta charset="UTF-8">

    <title>{{ page_title }} | Auth</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">

    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/page.css' %}">

  </head>

  <body>
<div class="widget effect">

  <div class="block-content">
  {% block content %}

  {% endblock content %}
    </div>

</div>

  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="{% static 'js/index.js' %}"></script>
  </body>

</html>

templates/base_login.html
<!doctype html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}PesaCrowd{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">
  {% load staticfiles %}
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
  <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico">

  <!-- CSS: implied media="all" -->
  {# load compress #}
  {# compress css #}
  {% block styles %}
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'css/smartmin_styles.css' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link type="text/css" rel="stylesheet" href="http://localhost:8888/pesacrowd/wp-content/themes/bizlight/assets/frameworks/bxslider/css/jquery.bxslider.css?ver=4.0">

  <!-- Theme upgrades -->
  <link rel='stylesheet' id='bizlight-googleapis-css'  href='//fonts.googleapis.com/css?family=Raleway%3A400%2C300%2C500%2C600%2C700%2C900&#038;ver=4.4.2' type='text/css' media='all' />
  <link rel='stylesheet' id='bizlight-googleapis-other-font-family-css'  href='//fonts.googleapis.com/css?family=Raleway&#038;ver=4.4.2' type='text/css' media='all' />
  <link rel='stylesheet' id='fontawesome-css'  href="{% static 'bizlight/frameworks/Font-Awesome/css/font-awesome.min.css' %}?ver=4.4.0" type='text/css' media='all' />
  <link rel='stylesheet' id='jquery-bxslider-css'  href="{% static 'bizlight/frameworks/bxslider/css/jquery.bxslider.css' %}?ver=4.0" type='text/css' media='all' />
  <link rel='stylesheet' id='animate-css'  href="{% static 'bizlight//frameworks/wow/css/animate.min.css' %}?ver=3.4.0" type='text/css' media='all' />
  <link rel='stylesheet' id='bizlight-style-css'  href="{% static 'bizlight/style.css' %}?ver=4.4.2" type='text/css' media='all' />

  {% endblock %}

  {% block extra-style %}{% endblock %}
    <script>
    if (window.location.hostname == "localhost"){
    document.write(unescape('%3Cscript src="{% static 'js/libs/jquery.1.11.1.min.js' %}"%3E%3C/script%3E'));
    } else {
    document.write(unescape('%3Cscript src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"%3E%3C/script%3E'));
    }
  </script>
  {# endcompress #}
</head>

<body>

  {% block navbar %}
  <header class="navbar navbar-static-top" role="banner">
    <div class="container">

      <div class="navbar-header">
	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#smartmin-navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
	</button>

	{% block brand %}
	<a class="navbar-brand" href="http://pesacrowd.com" target="_parent">PesaCrowd</a>
	{% endblock brand %}
      </div>

      {% block navigation %}
      <nav class="collapse navbar-collapse" id="smartmin-navbar-collapse" role="navigation">
	<ul class="nav navbar-nav navbar-right">
          <li>
            <a href="http://app.pesacrowd.com/web?page=invest-in-ambitious-businesses/" target="_parent">Invest With Us</a>
          </li>
          <li>
            <a href="http://app.pesacrowd.com/web?page=raise-funds-the-smart-way/" target="_parent">Raise Funds</a>
          </li>
          <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"> More <span class="caret"></span> </a>
              <ul class="dropdown-menu">
              <li><a href="http://app.pesacrowd.com/web?page=about" target="_parent">About us</a></li>
              <li><a href="http://app.pesacrowd.com/web?page=team" target="_parent">Team</a></li>
              <li><a href="http://app.pesacrowd.com/web?page=privacy-policy/" target="_parent">Privacy policy</a></li>
              <li><a href="http://app.pesacrowd.com/web?page=faqs/" target="_parent">FAQs</a></li>
              <li><a href="http://app.pesacrowd.com/web?page=contact-us/" target="_parent">Contact Us</a></li>
            </ul>
          </li>
	  {% block login %}
          {% if request.user and request.user.is_authenticated %}
          <li>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true"><img src="{{ MEDIA_URL }}{{ request.user.userprofile.profile_image }}" style="height: 40px;margin-bottom: -20px;margin-top: -20px;">My Account <span class="caret"></span> </a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'django_auth.userprofile_update' request.user.userprofile.id%}" target="_parent">Profile Settings</a></li>
              <li><a href="/" target="_parent" href="/" >My Portfolio</a></li>
              <li><a href="{% url 'logout' %}" target="_parent">logout</a></li>
            </ul>
          </li>
          {% else %}
          <li><a href="/login" target="_parent">Login</a></li>
                <li><a target="_parent" href="/login?tab=register">Register</a></li>

          {% endif %}
          {% endblock login %}
	</ul>
      </nav>
      {% endblock navigation %}

    </div>

  </header>
  {% endblock navbar %}

  <div class="container">

    {% load smartmin %}

    {% block content-div %}
    <div class="content">
      {% block messages %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        <a class="close" data-dismiss="alert">×</a>
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endblock messages %}

      {% block pre-content %}
      {% endblock %}

      {% block content %}
      {% endblock %}

      {% block post-content %}
      {% endblock %}
    </div>
    {% endblock %}

  </div> <!-- /container -->
  <footer class="footer">
      {% block footer %}
      Copyright &copy; 2016
      {% endblock %}
  </footer>

  {# compress js #}
  <script type="text/javascript" src="{% static 'js/jquery.pjax.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  {# media associated with any form we are displaying #}
  {% if form %}
  {{ form.media }}
  {% endif %}

  {% block extra-script %}{% endblock %}
  {% block script %}{% endblock %}
  {# endcompress #}

  <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
  <!--script type="text/javascript">
      var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));
      </script-->
</body>
</html>

templates/base_profile.html
<!DOCTYPE html>
<html >

  <head>

    <meta charset="UTF-8">

    <title>{{ page_title }} | Auth</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">

    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/page.css' %}">

  </head>

  <body>
<div class="widget effect">
  <ul>
    <li>Menu 1</li>
    <li>Menu 2</li>
    <li>Menu 3</li>
    <li>Menu 4</li>
  </ul>
  <div class="block-content">
  {% block content %}

  {% endblock content %}
    </div>
  <div class="avatar"><img src="http://maxme-life.ru/tests/prof_pic.jpg" /></div>
  <div class="desc">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ante est, condimentum eget commodo non, bibendum sed dolor.
  </div>
</div>

  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="{% static 'js/index.js' %}"></script>
  </body>

</html>

templates/confirm.html
{% extends "base_login.html" %}

{% block content %}

<div class="logmod">
  <div class="logmod__wrapper">
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-1"><a href="#">Email confirmed!</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">An SMS has been sent to your phone number {{phone}}. Enter the code below to complete the sign up process.</span>
             {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </div>
        <form action="/django_auth/confirm_reg_code/" method="post">{% csrf_token %}
        <div class="logmod__form">
            <div class="sminputs">

              <div class="input full">
                <label class="string optional" for="confirm_code">Confirmation code</label>
                <input id="confirm_code" maxlength="30" name="confirm_code" type="text" placeholder="Enter the confirmation code sent to you by SMS"/>
              </div>

            </div>
        </div>
          <div class="logmod__alter">
          <div class="logmod__alter-container">
              <div class="connect__context">
                <input type="submit" value="Submit"  class="connect googleplus"/>
              </div>
          </div>
        </div>
          </form>
      </div>
      </div>
    </div>
  </div>
    </div>
{% endblock %}

templates/confirm_login.html
{% extends "base_login.html" %}

{% block content %}

<div class="logmod">
  <div class="logmod__wrapper">
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-1"><a href="#">Complete Login!</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">An SMS has been sent to your phone number {{phone}}. Enter the code below to complete the log in process.</span>
             {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        </div>
        <form action="/django_auth/confirm_login_code/" method="post">{% csrf_token %}
        <div class="logmod__form">
            <div class="sminputs">
              <input type="hidden" name="username" value="{{ username }}">
              <input type="hidden" name="password" value="{{ password }}">
              <div class="input full">
                <label class="string optional" for="confirm_code">Confirmation code</label>
                <input id="confirm_code" maxlength="30" name="confirm_code" type="text" placeholder="Enter the confirmation code sent to you by SMS"/>
              </div>

            </div>
        </div>
          <div class="logmod__alter">
          <div class="logmod__alter-container">
              <div class="connect__context">
                <input type="submit" value="Submit"  class="connect googleplus"/>
              </div>
          </div>
        </div>
          </form>
      </div>
      </div>
    </div>
  </div>
    </div>
{% endblock %}

templates/invalid.html
{% extends "base.html" %}

{% block content %}

<h2>Invalid log in details</h2>

<p>
    <a href="/django_auth">Try again!</a>
</p>

{% endblock %}

templates/invalid_code.html
{% extends "base.html" %}

{% block content %}

<h2>Invalid code</h2>

<p>
    The confirmation code is invalid. Please<a href="/django_auth"> try again!</a>
</p>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
        <p class="error">Sorry, that's not a valid username or password</p>
    {% endif %}

    <form action="/django_auth/auth/" method="post">{% csrf_token %}
       <label for="username">User name:</label>
        <input type="text" name="username" value="" id="username">
        <label for="password">Password:</label>
        <input type="password" name="password" value="" id="password">

        <input type="submit" value="login"/>

        </form>
{% endblock %}

templates/login_register.html
{% extends "base_login.html" %}

{% block content %}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-error">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-error">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<script>
      $(document).ready(function(){
          $('#checkstuff').click(function() {

            if($('#id_terms').is(':checked')){
                $('#final_submit').click();
            }else{
                alert('You have to agree to the terms and conditions!')
            }
          });
          $(function () {
           var activeTab = $('[href=' + location.hash + ']');
           activeTab && activeTab.tab('show');
        });
      });
</script>

<div class="logmod">
  <div class="logmod__wrapper">
    <div class="logmod__container">
      <ul id="myTabs" class="nav nav-tabs" role="tablist">

                <li role="presentation" class="active"><a href="#login" role="tab" data-toggle="tab"
                                                          aria-controls="login" aria-expanded="false">Login</a></li>
                <li role="presentation" class=""><a href="#register" role="tab" data-toggle="tab"
                                                    aria-controls="register" aria-expanded="false">Register</a></li>
            </ul>
      <div id="myTabContent" class="tab-content" style="padding:20px;">
        <div role="tabpanel" class="tab-pane fade" id="register" aria-labelledby="register-tab">
          <div class="logmod__heading">
            <span class="logmod__heading-subtitle">Enter your personal details <strong>to create an acount</strong></span>
          </div>
          <form action="/django_auth/register/" method="post">{% csrf_token %}
          <div class="logmod__form">
              <div class="sminputs">
                <div class="input full">
                  <label class="string optional" for="id_email">Email*</label>
                  <input class="string optional" maxlength="255" id="id_email" name="email" placeholder="Email" type="email" size="50" />
                </div>
                <div class="input full">
                  <label class="string optional" for="username">Username*</label>
                  <input id="id_username" maxlength="30" name="username" type="text" placeholder="Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only"/>
                </div>
              </div>
              <div class="sminputs">
                <div class="input string optional">
                  <label class="string optional" for="id_password1">Password *</label>
                  <input class="string optional" maxlength="255" placeholder="Password" size="50" id="id_password1" name="password1" type="password"/>
                </div>
                <div class="input string optional">
                  <label class="string optional" for="id_password2">Repeat password *</label>
                  <input class="string optional" maxlength="255" placeholder="Password" size="50" id="id_password2" name="password2" type="password"/>

                </div>

                <div class="input full">
                  <label class="string optional" for="id_phone">Phone Number*</label>
                  <input id="id_phone" maxlength="30" name="phone" type="text" placeholder="Your mobile number"/>
                </div>
              </div>
          </div>
            <div class="logmod__alter">
            <div class="logmod__alter-container">

                <div class="" style="padding-top:10px; padding-bottom:10px;">
                  <input id="id_terms" maxlength="30" name="terms_of_service" type="checkbox" style="width:20px"/> I agree with the PesaCrowd <a href="http://www.pesacrowd.com/terms-of-use/" style="color: #028484">Terms & Conditions</a> and <a href="http://www.pesacrowd.com/privacy-policy/" style="color: #028484">Privacy Policy</a>
                </div>
                <div class="connect__context">
                  <a style="width:100% !important; text-align:center" class="button" id="checkstuff">Register</a>
                  <input style="display:none;" type="submit" value="Register"  class="connect facebook" id="final_submit"/>
                </div>
            </div>
          </div>
            </form>
        </div>
        <div role="tabpanel" class="tab-pane fade active in" id="login" aria-labelledby="login-tab">
          <div class="logmod__heading">
            {% if form.non_field_errors %}
                <ul class='form-errors'>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <span class="logmod__heading-subtitle">Enter your email and password <strong>to sign in</strong></span><br />
            {{confirmed}}
          </div>
            <form action="/django_auth/auth/" method="post">{% csrf_token %}
          <div class="logmod__form">
              <div class="sminputs">
                <div class="input full">
                  <label class="string optional" for="username">Username*</label>
                  <input class="string optional" type="text" name="username" value="" id="username" size="50" placeholder="Username">
                </div>
              </div>
              <div class="sminputs">
                <div class="input full">
                  <label class="string optional" for="user-pw">Password *</label>
                  <input class="string optional" maxlength="255" id="user-pw" placeholder="Password" type="password" size="50" name="password" />

                </div>
              </div>
              <div class="sminputs" style="text-align:center; font-size:0.9em">
                <a href='/user/forget'>Forgot password? Reset here.</a>
              </div>
          </div>
          <div class="logmod__alter">
            <div class="logmod__alter-container">
                <div class="connect__context">
                  <input style="width:100% !important" type="submit" value="Login"  class="connect googleplus"/>
                </div>
            </div>
          </div>
            </form>
            </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/no_user.html
{% extends "base.html" %}

{% block content %}

<h2>User not found</h2>

<p>
    Their is no user with those details. Please<a href="/django_auth"> try again!</a>
</p>

{% endblock %}

templates/page.html
<div class="widget effect">
  <ul>
    <li>Reviews</li>
    <li>Hotels</li>
    <li>Places</li>
    <li>Climate</li>
  </ul>
  <h2>Famous people living in Paris</h2>
  <div class="avatar"><img src="http://maxme-life.ru/tests/prof_pic.jpg" /></div>
  <div class="desc">
    <span class="name">Ernest Hemingway</span>
    <span class="header_address">Address in Paris:</span>
    <span class="address">74 rue du Cardinal Lemoine</span>
  </div>
</div>

templates/profile.html
{% extends "base_profile.html" %}

{% block content %}

<h2>Hi {{full_name}}!</h2>

<p>
    <a href="/django_auth/logout">Logout</a>
</p>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

    <h2>Register</h2>
    <form action="/django_auth/register/" method="post">{% csrf_token %}
        {{form}}
    <input type="submit" value="Register" />
    </form>

{% endblock %}

templates/register_success.html
{% extends "base.html" %}

{% block content %}

<h2>Registration success!</h2>

<p>
    Check your email to activate your account.
</p>

{% endblock %}